name: "SemGrep Analysis Workflow"

on:
  push:
    branches:
      - Master
jobs:
  semgrep_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: "Git :: Checkout"
        uses: actions/checkout@v2  # Use the latest stable version

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # 

      - name: "SemGrep :: Analysis"
        continue-on-error: true
        run: |
          pip install semgrep  # Install SemGrep
          semgrep ci --exclude-rule yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha --sarif --output=semgrep.sarif
        shell: bash
        env:
          # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable.
          SEMGREP_RULES: ${{ inputs.rules }}  # You can define 'inputs.rules' elsewhere

      - name: "GitHub Advanced Security :: Upload Sarif"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif

