name: "Security :: CodeQL - SemGrep"
  rules:  
    required: false
    default: "p/default"
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: "Git :: Checkout"
      uses: actions/checkout@v2

    - name: "SemGrep :: Analysis"
      run: |
        semgrep ci --exclude-rule yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha --sarif --output=semgrep.sarif
      shell: bash
      env:
        # Add the rules that Semgrep uses by setting the SEMGREP_RULES environment variable.
        SEMGREP_RULES: ${{ inputs.rules }} # more at semgrep.dev/explore

    - name: "GitHub Advanced Security :: Upload Sarif"
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: semgrep.sarif
      if: always()
