name: SemGrep Analysis

on:
  push:
    branches:
      - main

jobs:
  semgrep_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: "Git :: Checkout"
        uses: actions/checkout@v2

      - name: "SemGrep :: Analysis"
        run: |
          echo "Running SemGrep analysis"
          semgrep ci --exclude-rule yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha --sarif --output=semgrep.sarif
        shell: bash

      - name: "GitHub Advanced Security :: Upload Sarif"
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep.sarif
        if: always()

defaults:
  run:
    shell: bash
  env:
    SEMGREP_RULES: ${{ inputs.rules }}

# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
