name: "SemGrep Analysis Workflow"

on:
  push:
    branches:
      - master
jobs:
  semgrep_analysis:
    runs-on: ubuntu-latest

    steps:
      - name: "Git :: Checkout"
        uses: actions/checkout@v2

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: "SemGrep :: Analysis"
        continue-on-error: true
        run: |
          pip install semgrep
          semgrep ci --exclude-rule yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha --json > semgrep_results.json
        shell: bash

      - name: "Upload Analysis Results"
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-results
          path: semgrep_results.json
