name: Code Scanning

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  code-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Semgrep
        uses: returntocorp/semgrep-action@v1

      - name: Run Semgrep
        run: semgrep --config=p/security-audit /path/to/code

      - name: Setup CodeQL
        uses: github/codeql-action/setup@v1

      - name: Build CodeQL database
        run: |
          codeql database create codeql-db --language=python
          codeql database analyze codeql-db /path/to/code

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-results
          path: semgrep-results.json

      - name: Upload CodeQL results
        uses: actions/upload-artifact@v2
        with:
          name: codeql-results
          path: codeql-results.sarif
